account/urls.py
from django.conf.urls import include,url

from django.contrib.auth import views as auth_views

urlpatterns = [
	url(r'^login/$', auth_views.login,  {'template_name': 'account/registration/login.html'},name='login'),
	url(r'^logout/$', auth_views.logout,name='logout'),
	# url('', include('django.contrib.auth.urls')),
	# url(r'^transit$', views.transit, name='transit'),
	# url(r'^(?P<kw>[\w|\W]+)/(?P<cat>[\w|\W]+)/listing$', views.listing, name='listing'),
	# url(r'^(?P<cat>[\w|\W]+)/(?P<kw>[\w|\W]+)/listing$', views.listing, name='listing'),

]

buybuybiz/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^$','myaccount.views.index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/',include('account.urls', namespace="account")),
    url(r'^myaccount/',include('myaccount.urls', namespace="myaccount")),
    url(r'^messages/', include('postman.urls')),
]

myaccount/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^add/$',views.addProduct, name='addproduct'),
	url(r'^myproducts/$',views.myProducts, name='myproducts'),
	url(r'^edit/(?P<product_id>[0-9]+)/$',views.editProduct, name='editProduct'),
	url(r'^delete/(?P<product_id>[0-9]+)/$',views.delProduct, name='delProduct'),
	# url(r'^(?P<question_id>[0-9]+)/$',views.details,name='details'),
	# url(r'^login/$', auth_views.login,  {'template_name': 'account/registration/login.html'},name='login'),
	# url('', include('django.contrib.auth.urls')),
	# url(r'^transit$', views.transit, name='transit'),
	# url(r'^(?P<kw>[\w|\W]+)/(?P<cat>[\w|\W]+)/listing$', views.listing, name='listing'),
	# url(r'^(?P<cat>[\w|\W]+)/(?P<kw>[\w|\W]+)/listing$', views.listing, name='listing'),

]

myaccount/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class userData(models.Model):
	user = models.OneToOneField(User)
	sales = models.DecimalField(max_digits=11,decimal_places=2,default=0)
	orderNum = models.IntegerField(default=0)

class productCategory(models.Model):
	category = models.CharField(max_length=250,unique=True)
	# desc_chs = models.CharField(max_length=250)
	def __unicode__(self):
		return self.category

class Product(models.Model):
	name = models.CharField(max_length=200)
	description = models.TextField()
	quantity = models.DecimalField(max_digits=11,decimal_places=2)
	price = models.DecimalField(max_digits=11,decimal_places=2,default=0)
	sold_by = models.ForeignKey(User)
	category = models.ForeignKey(productCategory)
	def __unicode__(self):
		return self.name

class productPic(models.Model):
	product = models.ForeignKey(Product)
	picture = models.ImageField(upload_to='product_images',blank=True)
		

class orderStatus(models.Model):
	status = models.CharField(max_length=200,unique=True)
	def __unicode__(self):
		return self.status

class Order(models.Model):
	# sold_by = models.ForeignKey(User)
	bought_by = models.CharField(max_length=150)	
	status = models.ForeignKey(orderStatus)
	quantity = models.DecimalField(max_digits=11,decimal_places=2)
	orderDate = models.DateTimeField(auto_now_add=True)
	product = models.ForeignKey(Product)
	def __unicode__(self):
		return self.status

myaccount/forms.py
from django.forms import ModelForm
from myaccount.models import Product,productPic

class ProductForm(ModelForm):
	class Meta:
		model = Product
		fields = ['name','description','price','quantity','category']

class productPicform(ModelForm):
	class Meta:
		model = productPic
		fields = ['picture']
			
		

myaccount/views.py
from django.shortcuts import render,HttpResponse,HttpResponseRedirect
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from myaccount.models import userData, productCategory, Product, productPic,orderStatus, Order
from myaccount.forms import ProductForm, productPicform
from django.contrib import messages

import os
from django.conf import settings

# Create your views here.
@login_required
def index(request):
	productsCount = Product.objects.filter(sold_by=request.user).count()
	context = {'productsCount': productsCount}
	return render(request, 'myaccount/index.html', context)
    # return HttpResponse("Hello, world. You're at the polls index.")

@login_required
def addProduct(request):
	tflag = "add"
	# print request.user.id
	# A boolean value for telling the template whether the registration was successful.
	# Set to False initially. Code changes value to True when registration succeeds.
	# added = False
	
	if request.method == 'POST':
		product_form = ProductForm(request.POST)
		pic_form = productPicform(request.POST)
		if product_form.is_valid() :
			product = product_form.save(commit=False)
			product.sold_by = request.user
			product.save()
			# added = True
			# message = "Product: "+product.name+" is added successfullly."
			messages.success(request, 'Product: %s is successfullly added.' % product.name)

		if pic_form.is_valid():
			if 'picture' in request.FILES:
				pic = pic_form.save(commit=False)
				pic.product = product
				pic.picture = request.FILES['picture']
				pic.save()
		return HttpResponseRedirect(reverse('myaccount:myproducts'))
	else:
		product_form = ProductForm()
		pic_form = productPicform()

	context = {'product_form':product_form,'pic_form':pic_form}
	return render(request, 'myaccount/addproduct.html', context)
	# return HttpResponse("Hello, world. You're at the Add product.")

@login_required
def editProduct(request,product_id):
	tflag = "edit"
	# print request.user.id
	# A boolean value for telling the template whether the registration was successful.
	# Set to False initially. Code changes value to True when registration succeeds.
	# added = False
	p = Product.objects.get(pk=product_id)
	try:
		pic_pre = productPic.objects.get(product = p)
	except productPic.DoesNotExist:
		pic_pre = None
	if p.sold_by != request.user:
		return HttpResponse("You don't have permission")
	if request.method == 'POST':
		product_form = ProductForm(request.POST,instance=p)
		pic_form = productPicform(request.POST,instance=pic_pre)
		if product_form.is_valid():
			product = product_form.save(commit=False)
			product.sold_by = request.user
			product.save()
			# added = True
			messages.success(request, 'Product: %s is successfullly updated.' % product.name)

		if pic_form.is_valid():
			pic_new = pic_form.save(commit=False)
			pic_new.product = product
			if 'picture' in request.FILES:
				# Delete the old picture
				if pic_pre:
					os.remove(os.path.join(settings.MEDIA_ROOT,pic_pre.picture.name))
				pic_new.picture = request.FILES['picture']
				pic_new.save()

		return HttpResponseRedirect(reverse('myaccount:myproducts'))
	else:
		product_form = ProductForm(instance=p)
		pic_form = productPicform(instance=pic_pre)
	context = {'product_form':product_form,'pic_form':pic_form,'tflag':tflag, 'product_id':product_id}
	return render(request, 'myaccount/addproduct.html', context)
	# return HttpResponse("Hello, world. You're at the Add product.")

def delProduct(request,product_id):
	product = Product.objects.get(pk=product_id)
	try:
		pic = productPic.objects.get(product = product)
	except productPic.DoesNotExist:
		pic = None
	# pic = productPic.objects.get(product = product)
	if product.sold_by != request.user:
		return HttpResponse("You don't have permission")
	else:
		if pic:
			os.remove(os.path.join(settings.MEDIA_ROOT,pic.picture.name))
			pic.delete()
		messages.success(request, 'Product: %s is successfullly deleted.' % product.name)
		product.delete()
		return HttpResponseRedirect(reverse('myaccount:myproducts'))

@login_required
def myProducts(request):
	products = Product.objects.filter(sold_by=request.user)
	# paginator = Paginator(products,5)
	# page = request.GET.get('page')
	# try:
	# 	li = paginator.page(page)
	# except PageNotAnInteger:
	# 	li = paginator.page(1)
	# except EmptyPage:
	# 	li = paginator.page(paginator.num_pages)
	# context = {'listings':li}
	context = {'listings':products}
	return render(request, 'myaccount/myproducts.html', context)
	# return HttpResponse("Hello, world. You're at the polls index.")

myaccount/templates/myaccount/addproduct.html
{% extends "myaccount/myaccount_base.html" %}
{% load widget_tweaks %}

{% block page-header %}
{% if tflag != "edit" %}
Add Product
{% else %}
Edit Product
{% endif %}
{% endblock %}

{% block page-wrapper %}
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-body">
				<!-- <div class="col-lg-6"> -->
					{% if tflag != "edit" %}
					<form role="form" method="post" action="{% url 'myaccount:addproduct' %}" enctype="multipart/form-data">
					{% else %}
					<form role="form" method="post" action="{% url 'myaccount:editProduct' product_id %}" enctype="multipart/form-data">
					{% endif %}
						<div class="form-group">{% csrf_token %}</div>
						<div class="form-group">
							<label>Product Name</label>
							{% render_field product_form.name class="form-control" autofocus="" %}
						</div>
						<div class="form-group">
							<label>Product Description</label>
							{% render_field product_form.description class="form-control" %}
						</div>
						<div class="form-group">
							<label>Product Price</label>
							{% render_field product_form.price class="form-control" %}
						</div>
						<div class="form-group">
							<label>Product Quantity</label>
							{% render_field product_form.quantity class="form-control" %}
						</div>
						<div class="form-group">
							<label>Product Category</label>
							{% render_field product_form.category class="form-control" %}
						</div>
						<div class="form-group">
							<label>Product Picture</label>
							{% render_field pic_form.picture class="form-control" %}
						</div>
						<input type="submit" class="btn btn-lg btn-success btn-block" value="Submit" />
                        <!-- <input type="hidden" name="next" value="{{ next }}" /> -->
					</form>
				<!-- </div> -->
			</div>
		</div>
	</div>
</div>

<!-- <p>{{ request.user.get_profile.whatever }}</p> -->
<!-- <form action="{% url 'myaccount:addproduct' %}" method="post">
    {% csrf_token %}
    {{ product_form }}
    <input type="submit" value="Submit" />
</form> -->
{% endblock %}

myaccount/templates/myaccount/myaccount_base.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load staticfiles %}
{% load i18n %}{% load postman_tags %}

{% block head_css %}
<!-- MetisMenu CSS -->
<link href="{% static 'bower_components/metisMenu/dist/metisMenu.min.css' %}" rel="stylesheet">

<!-- Custom CSS -->
<link href="{% static 'myaccount/dist/css/sb-admin-2.css' %}" rel="stylesheet">

<!-- Custom Fonts -->
<link href="{% static 'bower_components/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block bodyblock %}
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'myaccount:index' %}">BuybuyBiz</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
            	<!-- <li> <a>Hello {{ user.get_username }}</a></li> -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-envelope fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-messages">
                    	<li>
                    		<a href="{% url 'postman_inbox' %}">
                    			<div>
                    				<i class="fa fa-comment fa-fw"></i>
                    				{% trans "Inbox" %}
                    				{% postman_unread as unread_count %}
                    				{% if unread_count %}
                    				<!-- <span class="pull-right text-muted small"> -->
                    				<span class = "badge pull-right">
                    	                {{ unread_count }}
                    	            </span>
                    	            {% endif %}
                    			</div>	
                    		</a>
                    	</li>
                    	<li class="divider"></li>

                    	<li>
                    		<a href="{% url 'postman_sent' %}">
                    			<div>
                    				<i class="fa fa-envelope fa-fw"></i>
                    				{% trans "Messages Sent" %}
                    			</div>	
                    		</a>
                    	</li>
                    	<li class="divider"></li>

                    	<li>
                    		<a href="{% url 'postman_write' %}">
                    			<div>
                    				<i class="fa fa-twitter fa-fw"></i>
                    				{% trans "Write Message" %}
                    			</div>	
                    		</a>
                    	</li>
                    	<li class="divider"></li>

                    	<li>
                    		<a href="{% url 'postman_archives' %}">
                    			<div>
                    				<i class="fa fa-archive fa-fw"></i>
                    				{% trans "Archives" %}
                    			</div>	
                    		</a>
                    	</li>
                    	<li class="divider"></li>
                    	
                    	<li>
                    		<a href="{% url 'postman_trash' %}">
                    			<div>
                    				<i class="fa fa-bitbucket fa-fw"></i>
                    				{% trans "Trash" %}
                    			</div>	
                    		</a>
                    	</li>
                    	

                    </ul>
                    <!-- /.dropdown-messages -->
                </li>
                
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                        </li>
                        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="{% url 'account:logout'%}?next={% url 'account:login'%}"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                <button class="btn btn-default" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                            </div>
                            <!-- /input-group -->
                        </li>
                        <li>
                            <a href="{% url 'myaccount:index' %}"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> My Products<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                            	<li><a href="{% url 'myaccount:addproduct' %}">Add Product</a></li>
                            	<li><a href="{% url 'myaccount:myproducts' %}">My Products</a></li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-wrench fa-fw"></i> My Orders<span class="fa arrow"></span></a>
                            <!-- <ul class="nav nav-second-level">
                                <li>
                                    <a href="panels-wells.html">Panels and Wells</a>
                                </li>
                                <li>
                                    <a href="buttons.html">Buttons</a>
                                </li>
                                <li>
                                    <a href="notifications.html">Notifications</a>
                                </li>
                                <li>
                                    <a href="typography.html">Typography</a>
                                </li>
                                <li>
                                    <a href="icons.html"> Icons</a>
                                </li>
                                <li>
                                    <a href="grid.html">Grid</a>
                                </li>
                            </ul> -->
                            <!-- /.nav-second-level -->
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>
        <div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">{% block page-header %}{% endblock %}</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
              {{message}}
        </div>
        {% endfor %}
        {% endif %}
        {% block page-wrapper %}{% endblock %}
        </div>
{% endblock %}

{% block js_block %}
<!-- Metis Menu Plugin JavaScript -->
<script src="{% static 'bower_components/metisMenu/dist/metisMenu.min.js' %}"></script>

<!-- Custom Theme JavaScript -->
<script src="{% static 'myaccount/dist/js/sb-admin-2.js' %}"></script>
{% endblock %}

myaccount/templates/myaccount/myproducts.html
{% extends "myaccount/myaccount_base.html" %}
{% load widget_tweaks %}
{% load i18n pagination_tags %}
{% block page-header %}My Products{% endblock %}

{% block page-wrapper %}
{% autopaginate listings 3 %}
{% if invalid_page %}
<p>{% trans "Sorry, this page number is invalid." %}</p>
{% else %}
{% if listings %}
<ul class="list-group">
	{% for p in listings %}
	<div class="panel panel-default">
		<div class="panel-heading">
		    <h3 class="panel-title">{{p.name}}</h3>
		    <!-- <a href="#" class="panel-title btn btn-outline btn-primary">Edit</a> -->
		</div>
		<div class="panel-body">
			<ul class="list-inline">
				<li class = "col-md-4"><b>Category</b>: {{p.category.category}}</li>
				<li class = "col-md-4"><b>Quantity</b>: {{p.quantity}} </li>
				<li class = "col-md-4"><b>Price</b>: {{p.price}} </li>
				<!-- <li class = "col-md-4"> </li> -->
			</ul>
			<hr>
			{% if p.productpic_set.all|length %}
			{% for image in p.productpic_set.all %}
			<div id="myCarousel" class="carousel slide col-md-4" data-ride="carousel">
				<div class="carousel-inner" role="listbox">
					
					<!-- if there is picture -->
					{% if forloop.counter == 1%}
					<div class="item active"><img src="{{ image.picture.url }}"></div>
					{% else %}
					<div class="item"><img src="{{ image.picture.url }}"></div>
					{% endif %}
				</div>
				<!-- Left and right controls -->
				  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
				    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
				    <span class="sr-only">Previous</span>
				  </a>
				  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
				    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
				    <span class="sr-only">Next</span>
				  </a>
			</div>
			{% endfor %}
			<p class = "col-md-8">{{p.description|truncatewords_html:100}}</p>
			{% else %}
			<p class = "col-md-4">{{p.description|truncatewords_html:100}}</p>
			{% endif %}
		</div>
		<div class="panel-footer">
			<a href="{% url 'myaccount:editProduct' p.id %}" class="btn btn-outline btn-success col-md-offset-2">Edit Product</a>
			<!-- Button trigger modal -->
			<button class="btn btn-outline btn-danger col-md-offset-4" data-toggle="modal" data-target="#product{{p.id}}">Delete Product</button>
			<!-- Modal -->
			<div class="modal fade" id="product{{p.id}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			    <div class="modal-dialog">
			        <div class="modal-content">
			            <div class="modal-header">
			                 <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
			                 <h4 class="modal-title" id="product{{p.id}}">Delete the Product?</h4>
			            </div>
			            <!-- <div class="modal-body">
			                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
			            </div> -->
			            <div class="modal-footer">
			                <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
			                <a href="{% url 'myaccount:delProduct' p.id %}" class="btn btn-danger">Yes</a>
			            </div>
			        </div>
			        <!-- /.modal-content -->
			    </div>
			    <!-- /.modal-dialog -->
			</div>
			<!-- /.modal -->
		</div>
	</div>
	<!-- <li class="list-group-item"></li> -->
	{% endfor %}
</ul>

<!-- Pager -->
<nav>
	{% paginate %}
</nav>
{% else %}
<div class="alert alert-danger">Sorry, you don't have any products</div>
{% endif %}
{% endif %}
{% endblock %}

myaccount/templates/myaccount/myproducts_bak.html
{% extends "myaccount/myaccount_base.html" %}
{% load widget_tweaks %}
{% load pagination_tags %}
{% block page-header %}My Products{% endblock %}

{% block page-wrapper %}

{% if listings %}
<ul class="list-group">
	{% for p in listings %}
	<div class="panel panel-default">
		<div class="panel-heading">
		    <h3 class="panel-title">{{p.name}}</h3>
		    <!-- <a href="#" class="panel-title btn btn-outline btn-primary">Edit</a> -->
		</div>
		<div class="panel-body">
			<ul class="list-inline">
				<li class = "col-md-4"><b>Category</b>: {{p.category.category}}</li>
				<li class = "col-md-4"><b>Quantity</b>: {{p.quantity}} </li>
				<li class = "col-md-4"><b>Price</b>: {{p.price}} </li>
				<!-- <li class = "col-md-4"> </li> -->
			</ul>
			<hr>
			{% if p.productpic_set.all|length %}
			{% for image in p.productpic_set.all %}
			<div id="myCarousel" class="carousel slide col-md-4" data-ride="carousel">
				<div class="carousel-inner" role="listbox">
					
					<!-- if there is picture -->
					{% if forloop.counter == 1%}
					<div class="item active"><img src="{{ image.picture.url }}"></div>
					{% else %}
					<div class="item"><img src="{{ image.picture.url }}"></div>
					{% endif %}
				</div>
				<!-- Left and right controls -->
				  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
				    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
				    <span class="sr-only">Previous</span>
				  </a>
				  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
				    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
				    <span class="sr-only">Next</span>
				  </a>
			</div>
			{% endfor %}
			<p class = "col-md-8">{{p.description|truncatewords_html:100}}</p>
			{% else %}
			<p class = "col-md-4">{{p.description|truncatewords_html:100}}</p>
			{% endif %}
		</div>
		<div class="panel-footer">
			<a href="{% url 'myaccount:editProduct' p.id %}" class="btn btn-outline btn-success col-md-offset-2">Edit Product</a>
			<!-- Button trigger modal -->
			<button class="btn btn-outline btn-danger col-md-offset-4" data-toggle="modal" data-target="#product{{p.id}}">Delete Product</button>
			<!-- Modal -->
			<div class="modal fade" id="product{{p.id}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			    <div class="modal-dialog">
			        <div class="modal-content">
			            <div class="modal-header">
			                 <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
			                 <h4 class="modal-title" id="product{{p.id}}">Delete the Product?</h4>
			            </div>
			            <!-- <div class="modal-body">
			                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
			            </div> -->
			            <div class="modal-footer">
			                <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
			                <a href="{% url 'myaccount:delProduct' p.id %}" class="btn btn-danger">Yes</a>
			            </div>
			        </div>
			        <!-- /.modal-content -->
			    </div>
			    <!-- /.modal-dialog -->
			</div>
			<!-- /.modal -->
		</div>
	</div>
	<!-- <li class="list-group-item"></li> -->
	{% endfor %}
</ul>

<!-- Pager -->
<nav>
	<ul class="pagination">
		{% if listings.has_previous %}
		<li><a href="?page={{ listings.previous_page_number }}"><span aria-hidden="true">&laquo; Prev</span></a></li>
		{% else %}
		<li class="disabled"><a href="#"><span aria-hidden="true">&laquo; Prev</span></a></li>
		{% endif %}
		{% if listings.paginator.num_pages < 8 %}
			{% for i in listings.paginator.page_range %}
				{% if i == listings.number %}
				<li class="active"><a href="#">{{ i }} <span class="sr-only">(current)</span></a></li>
				{% else %}
				<li><a href="?page={{i}}">{{i}}</a></li>
				{% endif %}
			{% endfor%}
		{% elif listings.number < 4 %}
			{% for i in listings.paginator.page_range|slice:":3"%}
				{% if i == listings.number %}
					<li class="active"><a href="#">{{ i }} <span class="sr-only">(current)</span></a></li>
					{% else %}
					<li><a href="?page={{i}}">{{i}}</a></li>
				{% endif %}
			{% endfor %}
			{% if listings.number == 3 %}
			<li><a href="?page=4">4</a></li>
			{% endif %}
			<li><span>...</span></li>
			<li><a href="?page={{listings.paginator.num_pages}}">{{listings.paginator.num_pages}}</a></li>
		{% elif listings.number > listings.paginator.num_pages|add:"-3" %}
			<li><a href="?page=1">1</a></li>
			<li><span>...</span></li>
			{% if listings.number == listings.paginator.num_pages|add:"-2" %}
				<li><a href="?page={{listings.paginator.num_pages|add:"-3"}}">{{listings.paginator.num_pages|add:"-3"}}</a></li>
			{% endif%}
			{% for i in listings.paginator.page_range|slice:"-3:" %}
				{% if i == listings.number %}
					<li class="active"><a href="#">{{ i }} <span class="sr-only">(current)</span></a></li>
				{% else %}
					<li><a href="?page={{i}}">{{i}}</a></li>
				{% endif %}
			{% endfor %}
		{% else %}
			<li><a href="?page=1">1</a></li>
			<li><span>...</span></li>
			<li><a href="?page={{listings.number|add:"-1"}}">{{listings.number|add:"-1"}}</a></li>
			<li class="active"><a href="?page={{listings.number}}">{{listings.number}} <span class="sr-only">(current)</span></a></li>
			<li><a href="?page={{listings.number|add:"1"}}">{{listings.number|add:"1"}}</a></li>
			<li><span>...</span></li>
			<li><a href="?page={{listings.paginator.num_pages}}">{{listings.paginator.num_pages}}</a></li>
		{% endif %}
		{% if listings.has_next %}
			<li><a href="?page={{ listings.next_page_number }}"><span aria-hidden="true">Next &raquo;</span></a></li>
		{% else %}
			<li class="disabled"><a href="#"><span aria-hidden="true">Next &raquo;</span></a></li>
		{% endif %}
	</ul>
</nav>
{% else %}
<div class="alert alert-danger">Sorry, you don't have any products</div>
{% endif %}
{% endblock %}